// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// margins_dim
Rcpp::IntegerVector margins_dim(std::string fname, std::string group);
RcppExport SEXP _hdf5tenx_margins_dim(SEXP fnameSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(margins_dim(fname, group));
    return rcpp_result_gen;
END_RCPP
}
// margins_rle_slab
Rcpp::List margins_rle_slab(const std::string fname, const std::string group, const int bufsize, const int begin, const int end);
RcppExport SEXP _hdf5tenx_margins_rle_slab(SEXP fnameSEXP, SEXP groupSEXP, SEXP bufsizeSEXP, SEXP beginSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< const std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const int >::type bufsize(bufsizeSEXP);
    Rcpp::traits::input_parameter< const int >::type begin(beginSEXP);
    Rcpp::traits::input_parameter< const int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(margins_rle_slab(fname, group, bufsize, begin, end));
    return rcpp_result_gen;
END_RCPP
}
// margins_dense_slab
Rcpp::List margins_dense_slab(const std::string fname, const std::string group, const int bufsize, const int begin, const int end);
RcppExport SEXP _hdf5tenx_margins_dense_slab(SEXP fnameSEXP, SEXP groupSEXP, SEXP bufsizeSEXP, SEXP beginSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< const std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const int >::type bufsize(bufsizeSEXP);
    Rcpp::traits::input_parameter< const int >::type begin(beginSEXP);
    Rcpp::traits::input_parameter< const int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(margins_dense_slab(fname, group, bufsize, begin, end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdf5tenx_margins_dim", (DL_FUNC) &_hdf5tenx_margins_dim, 2},
    {"_hdf5tenx_margins_rle_slab", (DL_FUNC) &_hdf5tenx_margins_rle_slab, 5},
    {"_hdf5tenx_margins_dense_slab", (DL_FUNC) &_hdf5tenx_margins_dense_slab, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdf5tenx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
