# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tenx_margins <- function(r_fname, r_group, r_bufsize) {
    .Call(`_hdf5tenx_tenx_margins`, r_fname, r_group, r_bufsize)
}

tenx_margins_slab <- function(r_fname, r_group, r_offset, r_count) {
    .Call(`_hdf5tenx_tenx_margins_slab`, r_fname, r_group, r_offset, r_count)
}

