# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indptr <- function(fname, group) {
    .Call(`_hdf5tenx_indptr`, fname, group)
}

margins_dim <- function(fname, group) {
    .Call(`_hdf5tenx_margins_dim`, fname, group)
}

margins_rle_slab <- function(fname, group, indptr, begin, end) {
    .Call(`_hdf5tenx_margins_rle_slab`, fname, group, indptr, begin, end)
}

margins_dense_slab <- function(fname, group, nrow, begin, end) {
    .Call(`_hdf5tenx_margins_dense_slab`, fname, group, nrow, begin, end)
}

